### ISSUE TITLE
i386 replay instruction discrepancy detected

### ISSUE THREAD

**Issue by senjitsu** [panda-re/panda#225] opened 2017-10-22 17:21 UTC
Hello! I am currently experiencing an issue with replaying recordings. 

Running i386 running windows 2000, -cpu pentium3 -m 512 -vga cirrus and three isa-serial com port devices.

I get different disagreement errors for any given recording replay. The replay command I am using is identical to the normal run. The errors are usually a failed assertion somewhere in rr_log as some form of disagreement. I did originally have networking devices, and multiple HD's, but have tried to reduce to a minimally complete error reproduction.

The disagreement is usually pretty early in the replay, maybe 3-8% of the instructions. I have only recently tried debugging it a bit, but its a slow process as I need to refresh my gdb knowledge.

I know I saw something about Mozilla RR, but cant seem to find the link on it. I may be able to use that to debug this a bit more.

**Comment by moyix** [comment] 2017-10-22 21:55
Sure. RR is [Mozilla rr](http://rr-project.org/). `diverge.py` can be found in `panda/scripts/diverge.py`; it takes two `rr` recordings (one of the PANDA recording and one of the PANDA replay) and then replays them under `rr`. It searches for the first point where the state of the system diverges (i.e., memory or CPU state is different from what it should be), and then tries to backtrack to find the cause of that divergence.

**Comment by senjitsu** [comment] 2017-10-22 23:47
Interesting concept, Hopefully I can find something of interest from this.

**Comment by senjitsu** [comment] 2017-10-23 14:20
Just out of curiosity, does anybody have Mozilla RR built and all tests passing on Ubuntu 16.04? I have about 25% of tests failing, I dont want that to skew anything for looking at panda...

**Comment by senjitsu** [comment] 2017-10-24 12:04
I could really use a i386 replay file that is known good. It looks like the replay files from PandaShare are primarily using Panda 1. I want to test that my build function with a control.

**Comment by moyix** [comment] 2017-10-24 19:16
You can use run_debian to get a replay file that works (or if it doesn't, then that's a much more obvious bug!).

```
$ cd build
$ ../panda/scripts/run_debian.py ls
```

That will record "ls" running on an i386 Debian VM.

**Comment by senjitsu** [comment] 2017-10-24 20:46
Alright I will give that a shot. Here is some info from what I have gathered. 

So I am not able to get recording / replays that will even fully process every attempt, sometimes I get the infinite loop assertion, sometimes, it hangs when loading the .log file and cpu goes idle. 

But when I do get the mismatch to trigger in a replay, using mozilla RR processing with diverge.py, I have two data points. 

The first one is diverge is failing, within the find_precise_divergence function, ln 647 "local variable Hit is reference before assignment". Some helpful debugging info, record & replay instruction count is 0, the checksums do not match. 

The second datapoint, is able to get through diverge.py, with a stack trace that starts at clone.s:109. 

Pardon the ascii art it looks something like this

clone.s:109 -> pthread_create.c:333 ->qemu_tcg_cpu_thread -> tcg_cpu_exec -> cpu_exec ->cpu_handle_interrupt-> x86_cpu_exec_int:: seg_helper.c:1377 (arg cs is divergent) -> seg_helper.c:1262.

Seems to be a hardware interrupt, the divergence in terms of stack trace is apparent at the pthread_create.c, just going off memory addresses. (I am not sure if these strack traces should look IDENTICAL if things werent divergent.)

I will try to above script to gather another sample point. I am going to trying to get a few more divergence run's to completion, in hopes of getting more data points.

**Comment by moyix** [comment] 2017-10-28 16:34
Hmm, if the `cs` register is divergent as early as the x86 CPU init, then something is definitely off. What command line are you using for recording vs replay?

**Comment by senjitsu** [comment] 2017-11-03 13:58
So the VM run command options are as follows:

qemu-system-i386 -L /path/to/biosfolder/ -m 512 -vga cirrus -monitor stdio -hda /path/to/diskimg/ 

I create the recording with begin_record / end_record from the qemu terminal. 

The replay run command options are as follows:

qemu-system-i386 -L /path/to/biosfolder/ -replay replay_name -m 512 -vga cirrus -monitor stdio -hda /path/to/diskimg

The disk is a qcow2 disk image with Windows 2000 installed on it. I have removed some of the options from my original post in an attempt to isolate things with no luck.

**Comment by senjitsu** [comment] 2017-11-06 16:16
So my attempts at replaying the ls recording that occurs from the run_debian.py script are failing, where the replay command line I am using is as follows. 

sudo /opt/panda/build/i386-softmmu/qemu-system-i386 /home/user/.panda/wheezy_panda2.qcow2 -replay ls -loadvm root -display none

I am getting an instruction count discrepancy pretty early on, but I am not able to run the replay with all the same options that the script is using (the monitor / serial additions).

**Comment by moyix** [comment] 2017-11-06 19:05
Can you try replaying without the `-loadvm root` ? Just:

`opt/panda/build/i386-softmmu/qemu-system-i386 -replay ls`

**Comment by senjitsu** [comment] 2017-11-06 20:20
So it seems the replay completes successfully in that instance... When loading a replay file, what options are absolutely necessary to match between the vm run?

**Comment by moyix** [comment] 2017-11-07 15:38
I think the issue is not with the device options you were using, but rather that you were using `-loadvm`, which was loading a different snapshot at replay time. We may want to add something so that trying to use both `-replay` and `-loadvm` throws an error, since that combination can't possibly work (loading a snapshot and doing a replay at the same time doesn't make sense).

In general, though, that is a good question – and unfortunately not one that has a clean answer. The unhelpful answer is "whatever combination of options creates a set of emulated devices that allows the `-rr-snp` file to be restored as a QEMU snapshot". Just what that set of devices is varies by the platform you're trying to emulate. For i386, it should be okay to just specify the amount of memory (and even that can be omitted if the recording uses the default RAM size, 128MB).

**Comment by senjitsu** [comment] 2017-11-14 12:59
I will play with the options some more, I believe at the very least, I had to include the -vga cirrus otherwise I got some kind of memory mapping error. I am using the same amount of memory for the record / replay. I was specifying the boot harddrive for the replay, so I will take that off... Hopefully further reducing the options will show something promising...

**Comment by senjitsu** [comment] 2017-11-14 17:44
I reduced my test run against my Windows 2000 system to simply specifying the vm run options as

`-vga cirrus -monitor stdio `

and the replay options just including the `-vga cirrus` bit.

Allowing the default options for cpu / memory, many of my attempted recordings result in "infinite loop" detected assertion failures. I was able to get a run to at least get a discrepancy that is at a detectable instruction count (alot of my attempts at using the diverge.py, results it diverge.py failing because the discrepancy started at instruction count 0). 

I hope some of this output may be helpful in use honing in on what has been causing my struggles. 

From what I can see, the divergence is coming from a memory write. The first trace of interest is where it seems that the record / playback are still in sync. 
-------
Record
-------
memory_region_oldmmio_write_accessor::memory.c : 502
-------
Replay
-------
memory_region_write_accessor :: memory.c : 528

At this point, the write value, and size are equal, the target memory addressing is different, but I feel like this is the host's memory addressing, and should be different. 

Further up on the stack-trace, 

--------
Record
--------

Cpu_physical_memory_write_rom::exec.c : 2951
->apic_sync_vapic:apic.c : 125
->__memcpy_sse2_unaligned()

--------
Replay
--------
notdirty_mem_write::exec.c : 2104
(at this point I am still showing the same value, and write size as the above write_accessor calls)
->std_he_p::qemu/bswap.h : 343 

The last points in the previous record & replay is the top of the stack-trace. The stack traces look somewhat similar around the first chunk I describe above, but when the record side gets into the APIC calls, is where they diverge in terms of code calling. I am trying to fumble my way through the code to see if I can find anything more of use for the real developers.... If there is anything you info you could point me to that could help, please let me know.

**Comment by nathanjackson** [comment] 2018-03-26 15:17
I've created a PR to address this issue.

**Comment by moyix** [comment] 2019-09-17 21:14
Since this PR is merged, I will close.

**Closed by moyix** 2019-09-17 21:14 UTC
