### ISSUE TITLE
Translation not performed on pre-existing processes

### ISSUE THREAD

**Issue by wbierman** [panda-re/panda#201] opened 2017-08-01 02:44 UTC
Code translation is seemingly not performed for code running in processes that were created before introspection begins.  Doing so may be beyond the scope of PANDA, but I thought I'd raise the issue and find out.

**Comment by moyix** [comment] 2017-08-01 18:17
The cache of translated code (TB cache) should be flushed when a recording or replay starts. If you're trying to do analyses on a live system, you will need to explicitly flush the TB cache from your plugin.

**Comment by wbierman** [comment] 2017-08-01 18:38
This was while processing a recording.  I was unable to monitor system calls of processes which were launched before recording began.  `translate_callback()` in syscalls2.cpp was never called for those blocks, so system call points were never identified.

**Comment by phulin** [comment] 2017-08-08 15:01
It's definitely possible that the processes are somehow hidden from specific analyses if they start before the start of replay, but it's definitely impossible that code that runs is not getting translated. Are you sure that's what is going on?

**Comment by vigliag** [comment] 2017-10-28 13:28
I've encountered a similar problem, it may be the same. 
It doesn't make much sense for me either, but I had the `translate_callback()` not being executed until the TB cache is flushed at some later point (adding a `panda_do_flush_tb` during the plugin initialization doesn't seem to do anything, adding it later does the trick).

Maybe related, I also get unreadable basic blocks during the first phases of the replay:

```
loading snapshot
... done.
opening nondet log for read :   ./sysrec-rr-nondet.log
SYSENTER
SYSENTER
error while reading instruction from pc:1999114239
./sysrec-rr-nondet.log:  15128649973 instrs total.
sysrec:   151286508 (  1.00%) instrs.   79.45 sec.  0.68 GB ram.
error while reading instruction from pc:1891450879
error while reading instruction from pc:1973137407
error while reading instruction from pc:1970589695
error while reading instruction from pc:1999147007
error while reading instruction from pc:1825124351
sysrec:   302573016 (  2.00%) instrs.  136.20 sec.  0.75 GB ram.
SYSENTER
SYSENTER
sysrec:   453859503 (  3.00%) instrs.  200.34 sec.  0.77 GB ram.
error while reading instruction from pc:1973137407
error while reading instruction from pc:1969721343
error while reading instruction from pc:1813643263
error while reading instruction from pc:1999114239
sysrec:   605146002 (  4.00%) instrs.  276.88 sec.  0.77 GB ram.
error while reading instruction from pc:1999147007
```

Then later on (around 4% taint2 gets enabled and the tbs flushed) I start seeing syscalls "flowing" normally.

Relevant code generating those errors: https://github.com/vigliag/panda/blob/systaint/panda/plugins/systaint/syscall_listener.cpp#L120 (I've copied and adapted some code from syscalls2)

The fact that there are two `SYSENTER` between `opening nondet log for read` and `./sysrec-rr-nondet.log:  15128649973 instrs total.` might also be interesting.

**Comment by moyix** [comment] 2017-10-28 15:37
There are a few different issues mentioned here, but I can explain the unreadable instruction problem. If you look at the PCs it's trying to read:

```
In [1]: hex(1973137407)
Out[1]: '0x759bafff'

In [2]: hex(1969721343)
Out[2]: '0x75678fff'

In [3]: hex(1813643263)
Out[3]: '0x6c19ffff'

In [4]: hex(1999114239)
Out[4]: '0x77280fff'
```

They're all the last byte of the page. So when your plugin tries to read two bytes and the following page is not mapped (e.g., it may be paged out), you won't be able to read both bytes.

Since you are trying to read an instruction that is two bytes, then either: a) if the instruction actually is a `sysenter`, then QEMU will also try to read two bytes and encounter a page fault when it gets to the second byte, and will not translate the instruction until the page fault is serviced; b) the instruction may just be one byte, in which case you don't care anyway, since `sysenter` is two bytes.

So your code should be working correctly and not missing any system calls.

As for the problem with the missing translate callbacks, I don't know – I don't think I've seen this. If we have a clear test case it would be possible to investigate.

**Comment by vigliag** [comment] 2017-10-28 16:22
Interesting, thanks a lot! I had completely missed the page boundary, and I don't know much in general about how qemu handles page faults.

I'll try again with the systemcall detection and let you know if I can reproduce. I remember being able to observe the problem, but then I just went for the quickest workaround to get the other parts working.

**Comment by vigliag** [comment] 2017-10-28 17:44
Okay I may have figured out what's going on (not a problem with the translate_callback)
I can easily reproduce the problem by toggling a comment on `panda_do_flush_tb()` occurring around 2%.

```
without flushing tb at 2%

opening nondet log for read :	./sysrec-rr-nondet.log
translating SYSENTER, pc=1999270066 asid=533528576
translating SYSENTER, pc=1999270066 asid=237596672
./sysrec-rr-nondet.log:   783402885 instrs total.
sysrec:     7834033 (  1.00%) instrs.    3.26 sec.  0.59 GB ram.
sysrec:    15668059 (  2.00%) instrs.    5.54 sec.  0.60 GB ram.
sysrec:    23502088 (  3.00%) instrs.   10.63 sec.  0.63 GB ram.
sysrec:    31336120 (  4.00%) instrs.   14.16 sec.  0.63 GB ram.
sysrec:    39170148 (  5.00%) instrs.   18.85 sec.  0.65 GB ram.


flushing tb at 2%

opening nondet log for read :	./sysrec-rr-nondet.log
translating SYSENTER, pc=1999270066 asid=533528576
translating SYSENTER, pc=1999270066 asid=237596672
./sysrec-rr-nondet.log:   783402885 instrs total.
sysrec:     7834033 (  1.00%) instrs.    3.18 sec.  0.59 GB ram.
sysrec:    15668059 (  2.00%) instrs.    5.56 sec.  0.61 GB ram.
translating SYSENTER, pc=1999270066 asid=460103680
translating SYSENTER, pc=1999270066 asid=460103680
sysrec:    23502088 (  3.00%) instrs.   11.30 sec.  0.61 GB ram.
sysrec:    31336120 (  4.00%) instrs.   15.02 sec.  0.61 GB ram.
sysrec:    39170148 (  5.00%) instrs.   19.93 sec.  0.64 GB ram.
```

From what I see, the problem is about the way syscalls2 (and my plugin) works. I don't know how qemu works exactly, but I would assume it is possible that the same basic block is used by several processes, and translated only once.

If that's the case, then the problem would be that syscalls2 stores, when the instruction is translated, the pc together with the current asid. Then, in the exec_callback(), it doesn't do anything if the asid is not the same of when the block was translated. [relevant code](https://github.com/panda-re/panda/blob/master/panda/plugins/syscalls2/syscalls2.cpp#L420)

I've tried removing the asid check, and it seems to fix the problem (in that I can see all systemcalls without flushing the tb). Or at least, it seems to work with the way systemcalls are made on windows7Sp1 X86. This fix may break things on other OSs though.

**Comment by moyix** [comment] 2017-10-28 18:34
Ahhh, okay. I believe @evandowning is currently trying to debug this issue too. I'll paste here what I sent to him about why we introduced `syscallPCpoints` in the first place, since that seems to be the culprit. It would be great to get this fixed since it seems it's a longstanding problem:

> I'm not sure what's going wrong, but I can tell you what it's intended
> to be doing.
> 
> Suppose you have plugins A and B. Each wants to use translate/exec
> callbacks. Right now, since there is only one "exec callback" slot,
> both A and B will be called for each others' callbacks.
> 
> The solution here is intended to check, when plugin A receives an exec
> callback, whether it's one that was registered by plugin A. It does so
> by recording the PC and ASID during the translate callback and storing
> it in syscallPCpoints. Then at the exec callback it can see if it's at
> a PC and ASID where we previously registered a callback -- if not,
> then it's probably someone else's exec callback.
> 
> One implication is that this should never fail if you are only using
> one plugin with translate/exec callbacks. So there's definitely
> something wrong here! Maybe you can print out the PC/ASID at translate
> and exec time and see if there is a mismatch for some calls?
>

**Comment by vigliag** [comment] 2017-10-29 08:55
Maybe there are some simpler (although less elegant) fixes on the plugin side.

As far as I can tell, `insn_translate` and `insn_exec` both take the same parameters `(CPUState *env, target_ulong pc)`, so in theory, if the user is able to decide if the instruction is interesting on insn_translate, he should be able to repeat the same check on insn_exec.
For syscalls2, for example, it would mean reading those two bytes again in insn_exec, and verifying it is indeed a sysenter. It would require an additional read from memory and some duplicate code, but it shouldn't be bad performance-wise.

Another possible fix, if the actual check can't be repeated, could be storing and checking a different couple instead of the (pc,asid), for example (physical_address(pc), translation-block identifier), or (translation-block identifier, offset of the instruction in the tb).

Would one of these solutions work?

**Comment by moyix** [comment] 2017-10-29 15:11
It should work – that's pretty much what we were trying to do (in a different way) by checking the PC/ASID. I think one worry is that since the translated code gets cached by QEMU, it could be possible to have code that is executable but not readable any more. But we should be able to check experimentally if this is true (because the panda_virtual_memory_rw call would fail).

**Comment by wbierman** [comment] 2017-10-31 17:43
I'm not sure if we are all talking about the same problem, but the problem I reported was resolved by removing a branch prediction macro where PANDA hooks into QEMU, here: https://github.com/panda-re/panda/blob/master/target/i386/translate.c#L8486

**Comment by moyix** [comment] 2017-11-01 19:14
That would be a somewhat alarming bug – branch prediction macros aren't supposed to actually change the semantics of the code at all... do you have a test case we can try to reproduce?

**Comment by moyix** [comment] 2017-11-02 23:49
@vigliag I think I have tracked this down. QEMU tracks cached translation blocks by their *physical* address, not their virtual address. So the correct thing to use for the key is not the PC virtual address + ASID, but the physical address of the PC.

We could also try to replicate the exact information that QEMU uses to look up a cached translation block. It's something like:

```C
cpu_get_tb_cpu_state(env, &pc, &cs_base, &flags);
target_ulong phys_pc = panda_virt_to_phys(env, pc);
uint32_t h = tb_hash_func(phys_pc, pc, flags);
```

That should ensure that we end up with the same `h` at translation vs execution time.

**Comment by vigliag** [comment] 2017-11-03 07:12
Great to be able to look at the actual code. I had a look at the code referencing the `tb_hash_function` you found, it seems `h` is used for a hash-table lookup, then the tbs are compared by `tb_cmp` which compares the unhashed `pc, phyisical_address, cs_base, flags` in case of collisions. We could probably call `tb_cmp` directly from our code.
Although even using the hash directly is probably okay (there likelihood of collisions should be low), to have the absolute certainty the code being executed is the same code we labeled, we should probably also check that that code hasn't been overwritten, in which case qemu invalidates the tb if I recall correctly. 

By the way, I had submitted a PR using the other approach some days ago (and I forgot referencing it in this thread), which just checks a second time the code is actually a syscall, https://github.com/panda-re/panda/pull/228 but I can change it (it's really a few lines of code) if you think this approach is better.

**Comment by moyix** [comment] 2017-11-03 15:59
Thanks for the PR! I've merged it in its current form; the TB hash stuff might be a tiny bit faster, but system calls are infrequent enough (relative to other instructions) that I don't think it makes a difference. I'll close this issue for now.

**Closed by moyix** 2017-11-03 15:59 UTC
