### ISSUE TITLE
OSI Linux kernelinfo utility can not be built with newer kernels.

### ISSUE THREAD

**Issue by mbakulin** [panda-re/panda#277] opened 2018-04-06 11:23 UTC
I was trying to build kernelinfo for latest Debian with kernel 4.9.0.6-686-pae, and it turns out, that some of the structures in the kernel has been changed, and kernelinfo is no longer buildable.

```
user@debian:~/kernelinfo$ make
make -C /lib/modules/4.9.0-6-686-pae/build M=/home/user/kernelinfo modules
make[1]: Entering directory '/usr/src/linux-headers-4.9.0-6-686-pae'
  CC [M]  /home/user/kernelinfo/kernelinfo.o
/home/user/kernelinfo/kernelinfo.c: In function ‘init_module’:
/home/user/kernelinfo/kernelinfo.c:61:132: error: ‘struct thread_info’ has no member named ‘task_offset’
 .%s_offset = %d", cfgname, cp_memb(#memb), (int)((void *)&(structp->memb) - (void *)structp))
                                                                   ^
/home/user/kernelinfo/kernelinfo.c:110:2: note: in expansion of macro ‘PRINT_OFFSET’
  PRINT_OFFSET(ti_p, task_offset,   "task");
  ^~~~~~~~~~~~
/usr/src/linux-headers-4.9.0-6-common/scripts/Makefile.build:304: recipe for target '/home/user/kernelinfo/kernelinfo.o' failed
make[4]: *** [/home/user/kernelinfo/kernelinfo.o] Error 1
/usr/src/linux-headers-4.9.0-6-common/Makefile:1515: recipe for target '_module_/home/user/kernelinfo' failed
make[3]: *** [_module_/home/user/kernelinfo] Error 2
Makefile:150: recipe for target 'sub-make' failed
make[2]: *** [sub-make] Error 2
Makefile:8: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-4.9.0-6-686-pae'
Makefile:4: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by wangray** [comment] 2018-05-18 22:08
Possible duplicate of https://github.com/panda-re/panda/issues/203?

**Closed** 2021-09-16 15:36 UTC
Labels: no-issue-activity
