### ISSUE TITLE
pandalog almost empty

### ISSUE THREAD

**Issue by rawsample** [panda-re/panda#357] opened 2018-10-02 13:13 UTC
Hello,

I am working on an Ubuntu 16.04 VM and when I try to generate a pandalog file with tainted_instr and/or tainted_branch, it is roughly empty.

To illustrate, here's what happens when I use the `taint_debian.py` script with a simple `base64 /etc/passwd`:
https://gist.github.com/rawsample/5a43bfa5cfc7b36e858eb5cc68f45409

I also reproduce the replay with some debug flags:
https://gist.github.com/rawsample/49ee89fee314a86c2b8f4cf4f2fbbead
The file is 'saw open' at line 261.

Everytime, the content of the pandalog file generated is the same:
```sh
[
{
  "pc": "18446744073709551615",
  "instr": "18446744073709551615"
}
]
```

`cpuid with invalid ptr in EAX: vaddr=0x0 paddr=0xffffffff. Probably not a Panda Hypercall` and `linux_read_enter for asid=0x7a4d000 fd=3 -- dont know about that asid. discarding` seem to be the only errors that could be related, but I can't figure out why none of read/write instructions are printed/logged.

**Comment by nathanjackson** [comment] 2018-10-05 01:02
I can confirm that I'm seeing similar results with `file_taint`. It looks like the associated system calls are were never detected or not properly detected.

**Comment by moyix** [comment] 2018-10-05 14:46
Looks like something is going wrong in the ASID/process tracking:

https://gist.github.com/rawsample/49ee89fee314a86c2b8f4cf4f2fbbead#file-replay_base64_debug-L261-L265

You can see that the file is being opened by ASID `0x7a4d000` but when the `read` call happens it thinks `0x7a4d000` is an unknown ASID.

Could both of you try again now that @m000's `osi_linux` improvements have been merged? Among other things it contains a fix that makes looking up the current process in Linux more reliable.

**Comment by moyix** [comment] 2018-10-05 14:50
As another workaround – I think this may be related to the `cache_process_details_on_basic_block` option which was added back in May. Previously we would check process details on every basic block; now they're only checked at system calls. Re-running file_taint with `cache_process_details_on_basic_block=1` should make it recognize the processes.

**Comment by nathanjackson** [comment] 2018-10-05 15:05
So I think I've got another piece to the puzzle. I'm pretty sure something isn't quite right about computing the return address in syscalls2 when a system call is invoked using sysenter. I've got a patch that seems to make file_taint work, but I need the `cache_process_details_on_basic_block=true` option on file taint, and @m000's `osi_linux` fixes.

With respect to the ASID\process tracking, do we actually need to do any of that for `file_taint`? At least for Linux, shouldn't registering a callback for `linux_read_return` be enough?

This is greatly simplified, but something like this is what I'm thinking:

```
void linux_read_return(CPUState *cpu, target_ulong pc, uint32_t fd,
                       uint32_t buf, uint32_t count)
{
    OsiProc *proc = get_current_process(cpu);
    char *filename = osi_linux_fd_to_filename(cpu, proc, fd);
    printf("read return filename=%s\n", filename);
    // Now taint the buffer....
}
```

**Comment by nathanjackson** [comment] 2018-10-05 15:08
Here's my syscalls patch. Thoughts?

https://github.com/nathanjackson/panda/commit/73ac55a258f7a64ca5e1b0c87cf777d452e9af93

**Comment by moyix** [comment] 2018-10-05 15:32
Hmm – I think the concern is that at the time Linux fd resolution wasn't reliable enough, so we wanted to just track the file descriptors per-process after `open`. But honestly `file_taint` has gotten to be a bit of a mess and has accumulated hacks over time. You can see that for `pread` we actually *do* use the `osi_linux_fd_to_filename` API:

https://github.com/panda-re/panda/blob/master/panda/plugins/file_taint/file_taint.cpp#L408-L413

As for your patch – do you have a 32-bit Linux test case where the return point calculated from the stack is different from `pc+11`? The magic `+11` comes from the assembly of the system call stub (which is in the RE stack exchange link):

```Dump of assembler code for function __kernel_vsyscall:
   0xf7ffd420 <+0>:        push   %ecx
   0xf7ffd421 <+1>:        push   %edx
   0xf7ffd422 <+2>:        push   %ebp
   0xf7ffd423 <+3>:        mov    %esp,%ebp
   0xf7ffd425 <+5>:        sysenter 
   0xf7ffd427 <+7>:        nop
   0xf7ffd428 <+8>:        nop
   0xf7ffd429 <+9>:        nop
   0xf7ffd42a <+10>:       nop
   0xf7ffd42b <+11>:       nop
   0xf7ffd42c <+12>:       nop
   0xf7ffd42d <+13>:       nop
   0xf7ffd42e <+14>:       int    $0x80
=> 0xf7ffd430 <+16>:       pop    %ebp
   0xf7ffd431 <+17>:       pop    %edx
   0xf7ffd432 <+18>:       pop    %ecx
   0xf7ffd433 <+19>:       ret    
End of assembler dump.```

The return stub is 11 bytes past the sysenter instruction (`0xf7ffd430-0xf7ffd425 = 11`).

But if they changed this in later 32-bit kernels then yes, we would need to do something different – is that what's going on here?

**Comment by nathanjackson** [comment] 2018-10-05 16:00
I'm wondering if the nop sled thing to int 80h block doesn't exist in my kernel\c library - wherever this lives. I had the thought maybe if I just disable the sysenter instruction (setting my CPU variant to pentium 1 on the PANDA\QEMU command-line), then the system calls would fallback to int 80h and file taint would work. Doing this instead caused a reboot loop. Setting it to Pentium II allowed me to boot. So I think whatever kernel I have may just not support the "legacy" system call style, but this test of changing the CPU variant is probably not detailed enough to know for sure.

The following minimal plugin code only ever printed read enter without the patch. With the patch, I see my read return as I expect.

```
void linux_read_enter(CPUState *cpu, target_ulong pc, uint32_t fd, uint32_t buf,
                      uint32_t count)
{
    OsiProc *proc = get_current_process(cpu);
    char *filename = osi_linux_fd_to_filename(cpu, proc, fd);
    printf("read enter filename=%s\n", filename);
}

void linux_read_return(CPUState *cpu, target_ulong pc, uint32_t fd,
                       uint32_t buf, uint32_t count)
{
    OsiProc *proc = get_current_process(cpu);
    char *filename = osi_linux_fd_to_filename(cpu, proc, fd);
    printf("read return filename=%s\n", filename);
}

bool init_plugin(void *self) {
    // Setup OSI
    panda_require("osi");
    assert(init_osi_api());

    panda_require("osi_linux");
    assert(init_osi_linux_api());

    // Setup syscalls2
    panda_require("syscalls2");
#ifdef TARGET_I386
    PPP_REG_CB("syscalls2", on_sys_read_enter, linux_read_enter);
    PPP_REG_CB("syscalls2", on_sys_read_return, linux_read_return);
#endif

    return true;
}
```

This was the source of the binary I'm testing:

```
#include <fcntl.h>
#include <stdint.h>
#include <stdio.h>
#include <sys/syscall.h>
#include <sys/types.h>
#include <unistd.h>

int main(int argc, char **argv) {
    if (argc < 2) {
      fprintf(stderr, "usage: %s <file name>\n", argv[0]);
      return 1;
    }

    int fd = open(argv[1], O_RDONLY);

    uint32_t value = 0;
    read(fd, &value, 255);

    if (value > 10) {
      printf("greater than 10\n");
    } else {
      printf("lte 10\n");
    }

    close(fd);

    return 0;
}
```

My recording is of Lubuntu 16.04. Unfortunately, I don't have a good way to share the actual recording at the moment. Let me figure out what I can do.

**Comment by rawsample** [comment] 2018-10-05 16:01
> But honestly `file_taint` has gotten to be a bit of a mess and has accumulated hacks over time. You can see that for `pread` we actually _do_ use the `osi_linux_fd_to_filename` API:
> 
> https://github.com/panda-re/panda/blob/master/panda/plugins/file_taint/file_taint.cpp#L408-L413
> 

Actually, I was waiting to find a way to fix this issue before proposing a cleaner on the file_taint plugin.
Until now I just rearrange the code for a better understanding and migrate codes to the header file.

https://gist.github.com/rawsample/a2515a25a8b613a2162bad16d3dca25b
https://gist.github.com/rawsample/6390f53c68cc8c13e6f3a71010cfaaef

**Comment by nathanjackson** [comment] 2018-10-08 13:47
@moyix Could I e-mail you a recording? I unfortunately I don't have a way to post to Dropbox or Google Drive, but I can transfer the recording to you via a link in an e-mail.

**Comment by moyix** [comment] 2018-10-08 14:55
Sure. brendandg@nyu.edu works.

**Comment by moyix** [comment] 2018-10-08 16:11
@nathanjackson 

Yep, it looks like your kernel/libc/whatever has the nops removed:

```
Breakpoint 1, 0xb772dc2d in ?? ()
(gdb) x/10i $pc
=> 0xb772dc2d:  sysenter
   0xb772dc2f:  int    $0x80
   0xb772dc31:  pop    %ebp
   0xb772dc32:  pop    %edx
   0xb772dc33:  pop    %ecx
   0xb772dc34:  ret  
```

And setting it to pc+4 instead does make it work.

Your patch to read the return address off the stack appears to work for both, so if you make a PR of it I'd be happy to merge it.

It would still be nice to figure out how to get things to work without having to use `cache_process_details_on_basic_block` (or, at the very least, to enable that by default). Also, `osi_linux_fd_to_filename` seems to be a bit unreliable still (at least judging by the error messages it keeps spitting out) so it would be nice to see why it sometimes can't resolve things...

**Comment by moyix** [comment] 2018-10-08 17:13
@rawsample I think your issue is fixed by `cache_process_details_on_basic_block`, and @nathanjackson's issue is fixed via his PR just now. So I'm going to close this.

If someone wants to tackle reorganizing and cleaning up `file_taint`, please do submit a PR for it. It would also (while I'm dreaming) be nice to have some regression tests so we can do this kind of cleanup without much fear of breaking things – I know there is testing infrastructure, but I don't think we have any actual tests, and the PANDA-specific tests are not currently enabled in Travis.

**Closed by moyix** 2018-10-08 17:13 UTC

**Comment by rawsample** [comment] 2018-10-09 09:09
@moyix yes, now it works well thanks you.

One last issue is the `assert(no_taint || taint_enabled)` from `read_return()`.
https://github.com/panda-re/panda/blob/master/panda/plugins/file_taint/file_taint.cpp#L310

The option `enable_taint_on_open` has to be used to set `taint_enabled` to true for the assert.
Thus the second pass (first to figure out when to turn on taint, second to perform the analysis) from the `taint_debian.py` fails.

Do you think it is better to modify the python script to do only one pass with  `enable_taint_on_open=true` or keep the 2 passes and add a case in `file_taint.cpp` to set the bool `taint_enabled` correctly?

**Comment by moyix** [comment] 2018-10-09 17:59
Are you seeing that assert fail in `taint_debian.py` now? The intention of it was to allow the first pass to complete without an assertion failure (that's what the `notaint` portion of the if was for).

**Comment by rawsample** [comment] 2018-10-09 19:00
The first pass is [ok](https://gist.github.com/rawsample/d39a3c4d7b11207ed678d5f8ac7731b8#file-taint_debian-py-fail-2nd-pass-L99) with `no_taint` as you modified it, but the second pass [fails the assertion](https://gist.github.com/rawsample/d39a3c4d7b11207ed678d5f8ac7731b8#file-taint_debian-py-fail-2nd-pass-L169).
