### ISSUE TITLE
savevm hangs

### ISSUE THREAD

**Issue by Kojoley** [panda-re/panda#523] opened 2020-01-08 12:43 UTC
It is working with a year old pandas, so most probably was broken by QEMU update.

**Comment by nathanjackson** [comment] 2020-01-28 18:00
`savevm` seems to work okay for me, I actually make use of this quite often. Any chance you could share the guest image and configuration?

**Comment by Kojoley** [comment] 2020-01-28 23:27
The guest image is http://panda.moyix.net/~moyix/wheezy_panda2.qcow2, and I use `loadvm`, so probably it is qemu snapshot migration issue, I guess.

**Comment by Kojoley** [comment] 2020-02-05 18:37
It hangs even without `loadvm`, just `panda-system-i386 wheezy_panda2.qcow2 -serial stdio`.

**Comment by AndrewFasano** [comment] 2020-04-06 15:44
Are you still having this issue? It sounds like your qcow might've gotten corrupted because that exact qcow is fairly well tested and I haven't had any issues with it lately.

**Comment by Kojoley** [comment] 2020-04-06 16:11
A corrupted qcow should not hang the program, if so - it is a bug :-)
`sha1sum` for `wheezy_panda2.qcow2` is `1a944531ba019541a1242b9c2b450daf72518206`

P.S. There are commits in upstream about `savevm` hang https://lists.gnu.org/archive/html/qemu-devel/2017-05/msg04135.html

**Comment by AndrewFasano** [comment] 2020-04-09 00:22
We generally consider upstream QEMU issues out of scope for us to fix. QEMU bugs should be reported to the (much larger) QEMU dev team and once they're fixed upstream, we'll eventually get them merged into PANDA.

In cases like this where it looks like the bug may have been fixed upstream, you can backport those commits and make a PR if you'd like it to get fixed sooner. Otherwise, we'll get those changes merged in once we tackle #570.

**Comment by pcworld** [comment] 2021-05-15 02:43
I can reproduce this in the official Docker image.

```
$ sudo docker images
REPOSITORY                      TAG       IMAGE ID       CREATED         SIZE
pandare/panda                   latest    dfa6dc8a896d   3 days ago      2GB
$ sudo docker run --rm -it pandare/panda bash
root@08c7f6ba3115:/# cd /tmp                                                                             
root@08c7f6ba3115:/tmp# wget --no-check-certificate https://panda.moyix.net/~moyix/wheezy_panda2.qcow2
…
root@08c7f6ba3115:/tmp# sha256sum wheezy_panda2.qcow2 
890cbcc65fbce7ef65f5260eca36009f94207ec684b2da21f12531f1b1906f28  wheezy_panda2.qcow2
root@08c7f6ba3115:/tmp# sha1sum wheezy_panda2.qcow2 
a3f437109634612cf3a834fd59c36f16379357b5  wheezy_panda2.qcow2   # note that this differs from the one posted above
root@08c7f6ba3115:/tmp# panda-system-i386 wheezy_panda2.qcow2 -curses
```
The system boots into grub and switches to graphic mode, as expected. Press Alt-2 to switch to the monitor. Run `loadvm root`.
At this point, the panda/qemu process seems to hang (at least for several minutes), no way to switch back to the VGA or serial console via Alt-num, SIGTERM does nothing, only SIGKILL is able to kill the panda/qemu process.
Note that even using invalid tags such as `loadvm asdf` hangs the process. (savevm does too.)
I have tried applying the commits from https://lists.gnu.org/archive/html/qemu-devel/2017-05/msg04135.html ("block: fix 'savevm' hang with -object iothread"), that has not helped however.

The host OS (beneath the Docker) is Fedora 34.

**Comment by AndrewFasano** [comment] 2021-05-25 16:14
Thanks for the reproducibility details pcworld. I wouldn't have expected the invalid tag to hang PANDA. That will make things easier to track down if I find the cycles to try fixing this.

**Comment by pcworld** [comment] 2021-10-30 15:44
Regarding my comment https://github.com/panda-re/panda/issues/523#issuecomment-841587670 (which might be different from the original issue), I had found out later that when not using `-curses` but rather redirecting serial console to telnet (e.g., `-serial telnet:127.0.0.1:4444,server,wait`) and using `-monitor stdio`, `loadvm` works fine. Knowing this, it's not really a problem (maybe should be documented if a fix is not feasible).

**Closed** 2022-01-30 15:35 UTC
Labels: no-issue-activity
