### ISSUE TITLE
RR rr_assertion `current_item' failed in winxp sp3

### ISSUE THREAD

**Issue by bertcug** [panda-re/panda#212] opened 2017-08-22 07:05 UTC
I make a simple record in winxp sp3, when replay it occurs this error. I can replay success in `win7 x86` and `ubuntu server 12.04`, the picture show the process how I made record and replay.
![xp error](https://user-images.githubusercontent.com/6436893/29552609-a6d900a6-874a-11e7-8252-b3b3a8a65eb5.png)
so does any one replay success in winxp ?
```
bert@kenwu:~/images$ panda_i386 -m 2048 winxpsp3_86.img --monitor stdio
QEMU 2.8.50 monitor - type 'help' for more information
(qemu) Could not initialize SDL(No available video device) - exiting
bert@kenwu:~/images$ panda_i386 -m 2048 winxpsp3_86.img --monitor stdio -vnc :2
QEMU 2.8.50 monitor - type 'help' for more information
(qemu) begin_record file_taint_test
(qemu) writing snapshot:	./file_taint_test-rr-snp
opening nondet log for write :	./file_taint_test-rr-nondet.log
end_record
(qemu) Time taken was: 28 seconds.
Checksum of guest memory: 0xb40fe485
bert@kenwu:~/images$ ls
file_taint_test-rr-nondet.log  file_taint_test-rr-snp  ubuntu12.04.qcow2  win7sp1_86.img  winxpsp3_86.img
bert@kenwu:~/images$ panda_i386 -m 2048 -replay file_taint_test
loading snapshot
... done.
opening nondet log for read :	./file_taint_test-rr-nondet.log
RR rr_assertion `current_item' failed at /home/kenwu/Documents/panda2.0/panda/panda/src/rr/rr_log.c:813
Current log point:
{guest_instr_count=696}
Next log entry type: RR_INPUT_4
Current replay point:
{guest_instr_count=692}
Aborted (core dumped)
```

**Comment by bertcug** [comment] 2017-08-22 07:08
@antverdovsky do you have any experice on replay in winxp ?

**Comment by antverdovsky** [comment] 2017-08-22 21:47
@bertcug, no I have only used it with a x86 Debian guest. Also, this looks like a possible duplicate of #195.

**Comment by bertcug** [comment] 2017-08-24 00:58
I test winxp in panda1,  the replay works. but with the same image, it doesn't work with panda2. everytime I use panda2 to start winxp, when the os started, a "Found New Hardware Wizard" windows start up, may be this is where the problem is.
![xp](https://user-images.githubusercontent.com/6436893/29644636-4d7f2e34-88aa-11e7-8a4a-8c72b873cf75.png)
@moyix

**Comment by bertcug** [comment] 2017-08-24 01:28
I use panda1 test replay with xpsp3, I got this:
```
bert@kenwu:~$ ./panda1/qemu/i386-softmmu/qemu-system-i386 -m 2048 -replay ./replays/cal -usbdevice tablet -panda osi -panda osi_winxpsp3x86 -panda osi_test -os windows-32-xpsp3
adding /home/bert/panda1/qemu/i386-softmmu/panda_plugins/panda_osi.so to panda_plugin_files 0
adding /home/bert/panda1/qemu/i386-softmmu/panda_plugins/panda_osi_winxpsp3x86.so to panda_plugin_files 1
adding /home/bert/panda1/qemu/i386-softmmu/panda_plugins/panda_osi_test.so to panda_plugin_files 2
os_type=1 bits=32 os_details=[xpsp3]
loading /home/bert/panda1/qemu/i386-softmmu/panda_plugins/panda_osi.so
OSI grabbing Windows introspection backend.
panda_require: win7x86intro
loading /home/bert/panda1/qemu/i386-softmmu/panda_plugins/panda_win7x86intro.so
Success
panda_require: wintrospection
loading /home/bert/panda1/qemu/i386-softmmu/panda_plugins/panda_wintrospection.so
Initializing plugin wintrospection
qemu-system-i386: wintrospection.c:374: init_plugin: Assertion `0 == __extension__ ({ size_t __s1_len, __s2_len; (__builtin_constant_p (panda_os_details) && __builtin_constant_p ("7") && (__s1_len = __builtin_strlen (panda_os_details), __s2_len = __builtin_strlen ("7"), (!((size_t)(const void *)((panda_os_details) + 1) - (size_t)(const void *)(panda_os_details) == 1) || __s1_len >= 4) && (!((size_t)(const void *)(("7") + 1) - (size_t)(const void *)("7") == 1) || __s2_len >= 4)) ? __builtin_strcmp (panda_os_details, "7") : (__builtin_constant_p (panda_os_details) && ((size_t)(const void *)((panda_os_details) + 1) - (size_t)(const void *)(panda_os_details) == 1) && (__s1_len = __builtin_strlen (panda_os_details), __s1_len < 4) ? (__builtin_constant_p ("7") && ((size_t)(const void *)(("7") + 1) - (size_t)(const void *)("7") == 1) ? __builtin_strcmp (panda_os_details, "7") : (__extension__ ({ const unsigned char *__s2 = (const unsigned char *) (const char *) ("7"); int __result = (((const unsigned char *) (const char *) (panda_os_details))[0] - __s2[0]); if (__s1_len > 0 && __result == 0) { __result = (((const unsigned char *) (const char *) (panda_os_details))[1] - __s2[1]); if (__s1_len > 1 && __result == 0) { __result = (((const unsigned char *) (const char *) (panda_os_details))[2] - __s2[2]); if (__s1_len > 2 && __result == 0) __result = (((const unsigned char *) (const char *) (panda_os_details))[3] - __s2[3]); } } __result; }))) : (__builtin_constant_p ("7") && ((size_t)(const void *)(("7") + 1) - (size_t)(const void *)("7") == 1) && (__s2_len = __builtin_strlen ("7"), __s2_len < 4) ? (__builtin_constant_p (panda_os_details) && ((size_t)(const void *)((panda_os_details) + 1) - (size_t)(const void *)(panda_os_details) == 1) ? __builtin_strcmp (panda_os_details, "7") : (- (__extension__ ({ const unsigned char *__s2 = (const unsigned char *) (const char *) (panda_os_details); int __result = (((const unsigned char *) (const char *) ("7"))[0] - __s2[0]); if (__s2_len > 0 && __result == 0) { __result = (((const unsigned char *) (const char *) ("7"))[1] - __s2[1]); if (__s2_len > 1 && __result == 0) { __result = (((const unsigned char *) (const char *) ("7"))[2] - __s2[2]); if (__s2_len > 2 && __result == 0) __result = (((const unsigned char *) (const char *) ("7"))[3] - __s2[3]); } } __result; })))) : __builtin_strcmp (panda_os_details, "7")))); })' failed.
Aborted (core dumped)
```
in `wintrospection.c`:
```
bool init_plugin(void *self) {
#ifdef TARGET_I386
    // this stuff only currently works for win7 32-bit
    assert (panda_os_type == OST_WINDOWS);
    assert (panda_os_bits == 32);
    assert (0 == strcmp(panda_os_details, "7"));
    return true;
#else
    fprintf(stderr, "Plugin is not supported on this platform.\n");
    return false;
#endif
}
```
so, does panda1 support xpsp3 to replay ? as the code says it only works for win7 32-bit.

**Comment by bertcug** [comment] 2017-08-25 01:31
I solve the problem above just by comment this two lines in `os_intro.c`：
```
 if (panda_os_type == OST_WINDOWS) {
        g_printf("OSI grabbing Windows introspection backend.\n");
        //panda_require("win7x86intro");
        //panda_require("wintrospection");
    }
    return true;
}

void uninit_plugin(void *self) { }
```

the replay success:
```
$ ./i386-softmmu/qemu-system-i386 -m 2048 -usbdevice tablet -panda osi -panda osi_winxpsp3x86 -os windows-32-xpsp3 -panda asidstory -replay ~/replays/cal
adding /home/bert/panda1/qemu/i386-softmmu/panda_plugins/panda_osi.so to panda_plugin_files 0
adding /home/bert/panda1/qemu/i386-softmmu/panda_plugins/panda_osi_winxpsp3x86.so to panda_plugin_files 1
os_type=1 bits=32 os_details=[xpsp3]
adding /home/bert/panda1/qemu/i386-softmmu/panda_plugins/panda_asidstory.so to panda_plugin_files 2
loading /home/bert/panda1/qemu/i386-softmmu/panda_plugins/panda_osi.so
OSI grabbing Windows introspection backend.
Success
loading /home/bert/panda1/qemu/i386-softmmu/panda_plugins/panda_osi_winxpsp3x86.so
panda_require: osi
panda_load_plugin: /home/bert/panda1/qemu/i386-softmmu/panda_plugins/panda_osi.so already loaded
Success
loading /home/bert/panda1/qemu/i386-softmmu/panda_plugins/panda_asidstory.so
Initializing plugin asidstory
panda_require: osi
panda_load_plugin: /home/bert/panda1/qemu/i386-softmmu/panda_plugins/panda_osi.so already loaded
Success
loading snapshot
... done.
opening nondet log for read :	/home/bert/replays/cal-rr-nondet.log
max_instr = 42011861
cal:      424742 (  1.01%) instrs.    1.42 sec.  0.41 GB ram.
total_instr in replay:   42011861
cal:      843818 (  2.01%) instrs.    1.53 sec.  0.41 GB ram.
cal:     1629793 (  3.88%) instrs.    1.71 sec.  0.41 GB ram.
cal:     2074260 (  4.94%) instrs.    1.76 sec.  0.41 GB ram.
cal:     2187801 (  5.21%) instrs.    1.78 sec.  0.41 GB ram.
cal:     2550521 (  6.07%) instrs.    1.85 sec.  0.41 GB ram.
cal:     2964806 (  7.06%) instrs.    1.94 sec.  0.41 GB ram.
cal:     3388332 (  8.07%) instrs.    2.05 sec.  0.42 GB ram.
cal:     3794397 (  9.03%) instrs.    2.11 sec.  0.42 GB ram.
cal:     4256579 ( 10.13%) instrs.    2.18 sec.  0.42 GB ram.
cal:     4642387 ( 11.05%) instrs.    2.26 sec.  0.42 GB ram.
cal:     5063038 ( 12.05%) instrs.    2.35 sec.  0.42 GB ram.
cal:     5575150 ( 13.27%) instrs.    2.43 sec.  0.42 GB ram.
cal:     5912596 ( 14.07%) instrs.    2.48 sec.  0.42 GB ram.
cal:     6314952 ( 15.03%) instrs.    2.54 sec.  0.42 GB ram.
cal:     6761876 ( 16.10%) instrs.    2.62 sec.  0.42 GB ram.
cal:     7235871 ( 17.22%) instrs.    2.69 sec.  0.42 GB ram.
cal:     7614081 ( 18.12%) instrs.    2.75 sec.  0.42 GB ram.
cal:     8045685 ( 19.15%) instrs.    2.82 sec.  0.42 GB ram.
cal:     8515359 ( 20.27%) instrs.    2.89 sec.  0.42 GB ram.
cal:     8858039 ( 21.08%) instrs.    2.94 sec.  0.42 GB ram.
cal:     9260984 ( 22.04%) instrs.    3.02 sec.  0.42 GB ram.
cal:     9664123 ( 23.00%) instrs.    3.07 sec.  0.42 GB ram.
cal:    10101064 ( 24.04%) instrs.    3.12 sec.  0.42 GB ram.
cal:    10531613 ( 25.07%) instrs.    3.16 sec.  0.42 GB ram.
cal:    10926543 ( 26.01%) instrs.    3.22 sec.  0.42 GB ram.
cal:    12027836 ( 28.63%) instrs.    3.33 sec.  0.42 GB ram.
cal:    12027836 ( 28.63%) instrs.    3.33 sec.  0.42 GB ram.
cal:    12258901 ( 29.18%) instrs.    3.35 sec.  0.42 GB ram.
cal:    12667737 ( 30.15%) instrs.    3.41 sec.  0.42 GB ram.
cal:    13236004 ( 31.51%) instrs.    3.47 sec.  0.42 GB ram.
cal:    13592072 ( 32.35%) instrs.    3.50 sec.  0.42 GB ram.
cal:    13890030 ( 33.06%) instrs.    3.53 sec.  0.42 GB ram.
cal:    14319240 ( 34.08%) instrs.    3.60 sec.  0.42 GB ram.
cal:    14800278 ( 35.23%) instrs.    3.68 sec.  0.42 GB ram.
cal:    15144453 ( 36.05%) instrs.    3.72 sec.  0.42 GB ram.
cal:    15771771 ( 37.54%) instrs.    3.79 sec.  0.42 GB ram.
cal:    15983320 ( 38.04%) instrs.    3.82 sec.  0.42 GB ram.
cal:    16410900 ( 39.06%) instrs.    3.88 sec.  0.42 GB ram.
cal:    16946896 ( 40.34%) instrs.    3.93 sec.  0.42 GB ram.
cal:    17287889 ( 41.15%) instrs.    3.97 sec.  0.42 GB ram.
cal:    17813588 ( 42.40%) instrs.    4.03 sec.  0.42 GB ram.
cal:    18068035 ( 43.01%) instrs.    4.06 sec.  0.42 GB ram.
cal:    18562334 ( 44.18%) instrs.    4.12 sec.  0.42 GB ram.
cal:    18928899 ( 45.06%) instrs.    4.16 sec.  0.42 GB ram.
cal:    19333446 ( 46.02%) instrs.    4.21 sec.  0.42 GB ram.
cal:    19785713 ( 47.10%) instrs.    4.27 sec.  0.42 GB ram.
cal:    20214375 ( 48.12%) instrs.    4.36 sec.  0.42 GB ram.
cal:    20659669 ( 49.18%) instrs.    4.45 sec.  0.42 GB ram.
cal:    21018328 ( 50.03%) instrs.    4.50 sec.  0.42 GB ram.
cal:    21581031 ( 51.37%) instrs.    4.60 sec.  0.42 GB ram.
cal:    21876160 ( 52.07%) instrs.    4.65 sec.  0.42 GB ram.
cal:    22269989 ( 53.01%) instrs.    4.72 sec.  0.42 GB ram.
cal:    22863189 ( 54.42%) instrs.    4.80 sec.  0.42 GB ram.
cal:    23128067 ( 55.05%) instrs.    4.85 sec.  0.42 GB ram.
cal:    23561225 ( 56.08%) instrs.    4.91 sec.  0.42 GB ram.
cal:    23960754 ( 57.03%) instrs.    4.97 sec.  0.42 GB ram.
cal:    24370448 ( 58.01%) instrs.    5.04 sec.  0.42 GB ram.
cal:    24805605 ( 59.04%) instrs.    5.09 sec.  0.42 GB ram.
cal:    25372367 ( 60.39%) instrs.    5.22 sec.  0.42 GB ram.
cal:    25678328 ( 61.12%) instrs.    5.27 sec.  0.42 GB ram.
cal:    26102128 ( 62.13%) instrs.    5.34 sec.  0.42 GB ram.
cal:    26536305 ( 63.16%) instrs.    5.41 sec.  0.42 GB ram.
cal:    26911545 ( 64.06%) instrs.    5.47 sec.  0.42 GB ram.
cal:    27310850 ( 65.01%) instrs.    5.53 sec.  0.42 GB ram.
cal:    27975129 ( 66.59%) instrs.    5.65 sec.  0.43 GB ram.
cal:    28199538 ( 67.12%) instrs.    5.69 sec.  0.43 GB ram.
cal:    28654370 ( 68.21%) instrs.    5.76 sec.  0.43 GB ram.
cal:    29063425 ( 69.18%) instrs.    5.82 sec.  0.43 GB ram.
cal:    29527336 ( 70.28%) instrs.    5.88 sec.  0.43 GB ram.
cal:    29889567 ( 71.15%) instrs.    5.92 sec.  0.43 GB ram.
cal:    30292991 ( 72.11%) instrs.    5.98 sec.  0.43 GB ram.
cal:    30725806 ( 73.14%) instrs.    6.03 sec.  0.43 GB ram.
cal:    31141375 ( 74.13%) instrs.    6.08 sec.  0.43 GB ram.
cal:    31616058 ( 75.26%) instrs.    6.14 sec.  0.43 GB ram.
cal:    31944757 ( 76.04%) instrs.    6.18 sec.  0.43 GB ram.
cal:    32377263 ( 77.07%) instrs.    6.23 sec.  0.43 GB ram.
cal:    32807279 ( 78.09%) instrs.    6.29 sec.  0.43 GB ram.
cal:    33242886 ( 79.13%) instrs.    6.34 sec.  0.43 GB ram.
cal:    33615661 ( 80.01%) instrs.    6.39 sec.  0.43 GB ram.
cal:    34033981 ( 81.01%) instrs.    6.44 sec.  0.43 GB ram.
cal:    34475214 ( 82.06%) instrs.    6.50 sec.  0.43 GB ram.
cal:    34883686 ( 83.03%) instrs.    6.55 sec.  0.43 GB ram.
cal:    35349996 ( 84.14%) instrs.    6.61 sec.  0.43 GB ram.
cal:    35713033 ( 85.01%) instrs.    6.68 sec.  0.43 GB ram.
cal:    36141194 ( 86.03%) instrs.    6.78 sec.  0.43 GB ram.
cal:    36587897 ( 87.09%) instrs.    6.86 sec.  0.43 GB ram.
cal:    36974631 ( 88.01%) instrs.    6.93 sec.  0.43 GB ram.
cal:    37473482 ( 89.20%) instrs.    7.01 sec.  0.43 GB ram.
cal:    37940934 ( 90.31%) instrs.    7.09 sec.  0.43 GB ram.
cal:    38236967 ( 91.01%) instrs.    7.16 sec.  0.43 GB ram.
cal:    38685114 ( 92.08%) instrs.    7.23 sec.  0.43 GB ram.
cal:    39086320 ( 93.04%) instrs.    7.29 sec.  0.43 GB ram.
cal:    39535963 ( 94.11%) instrs.    7.36 sec.  0.43 GB ram.
cal:    40189230 ( 95.66%) instrs.    7.46 sec.  0.43 GB ram.
cal:    40740649 ( 96.97%) instrs.    7.51 sec.  0.43 GB ram.
cal:    40768358 ( 97.04%) instrs.    7.52 sec.  0.43 GB ram.
cal:    41186731 ( 98.04%) instrs.    7.57 sec.  0.43 GB ram.
cal:    41597443 ( 99.01%) instrs.    7.64 sec.  0.43 GB ram.
/home/bert/replays/cal-rr-nondet.log:  log is empty.
Replay completed successfully. 1
Time taken was: 7 seconds.
max_queue_len = 356
355 items on recycle list, 34080 bytes total
Replay completed successfully 2.
```

**Comment by moyix** [comment] 2017-08-25 22:02
I think the right fix for this is to add an extra case to distinguish between WinXP and Win7 in  `os_intro.c` and load the appropriate OSI plugin. If you do that then you won't need to explicitly load `osi_winxpsp3x86` as long as you specify `-os windows-32-xpsp3`.

**Comment by bertcug** [comment] 2017-08-26 08:55
yes，I have done it.
```
    if (panda_os_type == OST_WINDOWS && panda_os_bits == 32) {
        g_printf("OSI grabbing Windows introspection backend.\n");
        
        if(!strcmp(panda_os_details, "xpsp3")) 
            panda_require("osi_winxpsp3x86");
        else if(!strcmp(panda_os_details, "7")) {
            panda_require("win7x86intro");
            panda_require("wintrospection");
        }
    }
```

**Comment by bertcug** [comment] 2017-09-05 02:40
@antverdovsky  which linux os do you use for test ？ I tested on ubuntu 12.04， but I can get the right kernel info。

**Comment by antverdovsky** [comment] 2017-09-05 16:05
@bertcug Debian 7

**Comment by StablelJay** [comment] 2017-11-02 01:57
@bertcug I try ubuntu16.04, but I cannot get the right kernel info, so I cannot use osi_linux correctly, could it work in ubuntu12.04?

**Comment by bertcug** [comment] 2017-11-08 07:36
@StablelJay These codes used to get kernelinfo could compiled successfully on Debian 7， would failed on ubuntu 12.04. I've tried.

**Closed** 2018-07-06 18:20 UTC
