### ISSUE TITLE
Makefile:687: *** new RPATH too long - cannot adjust .so files for installation. Stop.

### ISSUE THREAD

**Issue by username7778** [panda-re/panda#922] opened 2021-03-27 10:00 UTC
hello
here is log: https://gist.github.com/username7778/232accfaa6159b9e0d4f6420ae435c25
how to fix?

thx

**Comment by lacraig2** [comment] 2021-03-28 23:48
There was a PR about this not too long ago #533. Maybe @LauraLMann has some advice?

**Comment by LauraLMann** [comment] 2021-03-29 10:56
It is possible to write PANDA plugins which use the RPATH in an .so file to load other PANDA plugins.  When PANDA is built, the RPATH in each .so file is set to the location in which the plugin was built.  But if the "make install" option is used, the plugins will be installed somewhere else and thus not be able to be found via the RPATH.  So #533 changed the "make install" option to use the chrpath utility to modify the RPATH in the .so files to correspond to the location where the plugins will be installed.  The problem is, this cannot be done if the desired new RPATH would be longer than the original RPATH.
So, you can change where you build PANDA so the original RPATH is longer than the path to the install location.
Or, you can change where you install PANDA so the new RPATH will be shorter than the path specified by the old RPATH.

**Comment by AndrewFasano** [comment] 2021-03-29 14:49
I've seen a PANDA fork that does this a little differently, and perhaps it's something we'd want to incorporate- they modified Makefile.target (Around line 233) file to add some LDFLAGS for the rpath:

```
$(PANDA_PROG): LDFLAGS+=-shared -Wl,-rpath '-Wl,$$ORIGIN:$$ORIGIN/../lib'
```

This then resolves the variable $ORIGIN at runtime (instead of compile time) which contains the path to the executable being run. [This post](https://stackoverflow.com/a/42347206) has more details and looks like it would work well here and remove the need for `chrpath`

**Closed** 2021-11-29 15:37 UTC
Labels: no-issue-activity
